<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SuperApp.Core\SuperApp.Core.csproj" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="mkdir &quot;$(SolutionDir)SmartApp\bin\$(Configuration)\$(TargetFramework)\Modules&quot; 2&gt;nul&#xD;&#xA;copy /Y &quot;$(TargetPath)&quot; &quot;$(SolutionDir)SmartApp\bin\$(Configuration)\$(TargetFramework)\Modules\&quot;" />
	</Target>

</Project>